#!/usr/bin/env python3
"""Build `data/top500.csv` -- the ranked pool the Round 3 draft deals from.

Why a checked-in snapshot instead of a live API call? Because the ranking is
the spine of the fairness constraint. If the pool changed between the draft
and the audit, "every hand sums to 2505" would be unverifiable. So the pool
is a file, with a date on it, in git.

The list below is a hand-maintained snapshot of large US-listed companies
(including ADRs, which trade on Alpaca like any other equity) with
approximate market caps in USD billions and approximate share prices.
**It is a starting point, not gospel.** Before Round 3, run:

    comp refresh-universe --metric market_cap

which re-prices every name from Alpaca and re-ranks, then writes the CSV
back with a fresh `as_of` date. Ranks only need to be a *consistent*
ordering for the draft to be fair -- but the fresher they are, the better
"most valuable" matches reality on the day.

Usage:
    python scripts/build_top500.py [--out data/top500.csv] [--size 500]
"""

from __future__ import annotations

import argparse
import csv
from datetime import date
from pathlib import Path

# (symbol, name, sector, market_cap_usd_billions, share_price_usd)
COMPANIES: list[tuple[str, str, str, float, float]] = [
    # ---- mega cap technology / platforms ----
    ("NVDA", "NVIDIA", "Technology", 4400, 180.0),
    ("MSFT", "Microsoft", "Technology", 3700, 500.0),
    ("AAPL", "Apple", "Technology", 3500, 235.0),
    ("GOOGL", "Alphabet Class A", "Communication Services", 2600, 215.0),
    ("AMZN", "Amazon.com", "Consumer Discretionary", 2400, 225.0),
    ("META", "Meta Platforms", "Communication Services", 1800, 710.0),
    ("AVGO", "Broadcom", "Technology", 1300, 275.0),
    ("TSLA", "Tesla", "Consumer Discretionary", 1100, 340.0),
    ("BRK.B", "Berkshire Hathaway Class B", "Financials", 1050, 485.0),
    ("TSM", "Taiwan Semiconductor ADR", "Technology", 1000, 250.0),
    ("LLY", "Eli Lilly", "Health Care", 800, 850.0),
    ("JPM", "JPMorgan Chase", "Financials", 780, 280.0),
    ("WMT", "Walmart", "Consumer Staples", 760, 95.0),
    ("V", "Visa", "Financials", 700, 355.0),
    ("ORCL", "Oracle", "Technology", 650, 230.0),
    ("MA", "Mastercard", "Financials", 530, 570.0),
    ("XOM", "Exxon Mobil", "Energy", 500, 115.0),
    ("NFLX", "Netflix", "Communication Services", 480, 1120.0),
    ("COST", "Costco Wholesale", "Consumer Staples", 430, 960.0),
    ("JNJ", "Johnson & Johnson", "Health Care", 420, 175.0),
    ("PLTR", "Palantir Technologies", "Technology", 400, 170.0),
    ("ASML", "ASML Holding ADR", "Technology", 400, 1000.0),
    ("HD", "Home Depot", "Consumer Discretionary", 400, 400.0),
    ("PG", "Procter & Gamble", "Consumer Staples", 390, 165.0),
    ("ABBV", "AbbVie", "Health Care", 370, 210.0),
    ("BAC", "Bank of America", "Financials", 360, 47.0),
    ("AMD", "Advanced Micro Devices", "Technology", 350, 215.0),
    ("SAP", "SAP ADR", "Technology", 340, 290.0),
    ("CRM", "Salesforce", "Technology", 320, 330.0),
    ("KO", "Coca-Cola", "Consumer Staples", 310, 72.0),
    ("CVX", "Chevron", "Energy", 300, 165.0),
    ("UNH", "UnitedHealth Group", "Health Care", 300, 330.0),
    ("BABA", "Alibaba Group ADR", "Consumer Discretionary", 300, 125.0),
    ("TMUS", "T-Mobile US", "Communication Services", 290, 250.0),
    ("WFC", "Wells Fargo", "Financials", 280, 82.0),
    ("MRK", "Merck & Co", "Health Care", 275, 110.0),
    ("CSCO", "Cisco Systems", "Technology", 270, 68.0),
    ("LIN", "Linde", "Materials", 265, 555.0),
    ("ACN", "Accenture", "Technology", 260, 415.0),
    ("TM", "Toyota Motor ADR", "Consumer Discretionary", 260, 195.0),
    ("ADBE", "Adobe", "Technology", 255, 580.0),
    ("NOW", "ServiceNow", "Technology", 250, 1200.0),
    ("PM", "Philip Morris International", "Consumer Staples", 250, 160.0),
    ("AZN", "AstraZeneca ADR", "Health Care", 250, 80.0),
    ("NVO", "Novo Nordisk ADR", "Health Care", 250, 55.0),
    ("PEP", "PepsiCo", "Consumer Staples", 245, 178.0),
    ("NVS", "Novartis ADR", "Health Care", 240, 120.0),
    ("MCD", "McDonald's", "Consumer Discretionary", 240, 335.0),
    ("GE", "GE Aerospace", "Industrials", 235, 215.0),
    ("TMO", "Thermo Fisher Scientific", "Health Care", 230, 600.0),
    ("IBM", "International Business Machines", "Technology", 225, 245.0),
    ("SHEL", "Shell ADR", "Energy", 220, 72.0),
    ("HSBC", "HSBC Holdings ADR", "Financials", 220, 62.0),
    ("ABT", "Abbott Laboratories", "Health Care", 220, 127.0),
    ("DIS", "Walt Disney", "Communication Services", 215, 118.0),
    ("ISRG", "Intuitive Surgical", "Health Care", 210, 590.0),
    ("QCOM", "Qualcomm", "Technology", 205, 185.0),
    ("AXP", "American Express", "Financials", 205, 290.0),
    ("GS", "Goldman Sachs", "Financials", 200, 640.0),
    ("SHOP", "Shopify", "Technology", 200, 155.0),
    ("CAT", "Caterpillar", "Industrials", 195, 400.0),
    ("MS", "Morgan Stanley", "Financials", 195, 122.0),
    ("TXN", "Texas Instruments", "Technology", 190, 208.0),
    ("APP", "AppLovin", "Technology", 190, 560.0),
    ("UBER", "Uber Technologies", "Industrials", 190, 90.0),
    ("VZ", "Verizon Communications", "Communication Services", 185, 44.0),
    ("RY", "Royal Bank of Canada", "Financials", 180, 130.0),
    ("INTU", "Intuit", "Technology", 180, 645.0),
    ("RTX", "RTX Corp", "Industrials", 175, 132.0),
    ("HDB", "HDFC Bank ADR", "Financials", 175, 72.0),
    ("T", "AT&T", "Communication Services", 170, 24.0),
    ("PDD", "PDD Holdings ADR", "Consumer Discretionary", 170, 120.0),
    ("AMGN", "Amgen", "Health Care", 165, 305.0),
    ("BKNG", "Booking Holdings", "Consumer Discretionary", 165, 5000.0),
    ("NEE", "NextEra Energy", "Utilities", 160, 78.0),
    ("SONY", "Sony Group ADR", "Consumer Discretionary", 160, 27.0),
    ("SPGI", "S&P Global", "Financials", 150, 480.0),
    ("BLK", "BlackRock", "Financials", 150, 990.0),
    ("DHR", "Danaher", "Health Care", 150, 205.0),
    ("ARM", "Arm Holdings ADR", "Technology", 150, 145.0),
    ("MUFG", "Mitsubishi UFJ Financial ADR", "Financials", 150, 15.0),
    ("INTC", "Intel", "Technology", 150, 32.0),
    ("PGR", "Progressive", "Financials", 155, 265.0),
    ("C", "Citigroup", "Financials", 145, 78.0),
    ("PFE", "Pfizer", "Health Care", 145, 26.0),
    ("LOW", "Lowe's Companies", "Consumer Discretionary", 145, 255.0),
    ("BA", "Boeing", "Industrials", 145, 190.0),
    ("UL", "Unilever ADR", "Consumer Staples", 145, 58.0),
    ("SPOT", "Spotify Technology", "Communication Services", 140, 690.0),
    ("HON", "Honeywell International", "Industrials", 140, 215.0),
    ("SCHW", "Charles Schwab", "Financials", 140, 78.0),
    ("SYK", "Stryker", "Health Care", 140, 365.0),
    ("BHP", "BHP Group ADR", "Materials", 135, 53.0),
    ("UNP", "Union Pacific", "Industrials", 135, 225.0),
    ("BSX", "Boston Scientific", "Health Care", 135, 92.0),
    ("MELI", "MercadoLibre", "Consumer Discretionary", 130, 2550.0),
    ("TTE", "TotalEnergies ADR", "Energy", 130, 58.0),
    ("BUD", "Anheuser-Busch InBev ADR", "Consumer Staples", 130, 65.0),
    ("SAN", "Banco Santander ADR", "Financials", 130, 9.0),
    ("SNY", "Sanofi ADR", "Health Care", 130, 52.0),
    ("CMCSA", "Comcast", "Communication Services", 130, 35.0),
    ("ETN", "Eaton", "Industrials", 130, 330.0),
    ("ANET", "Arista Networks", "Technology", 130, 105.0),
    ("MU", "Micron Technology", "Technology", 130, 115.0),
    ("AMAT", "Applied Materials", "Technology", 130, 160.0),
    ("GEV", "GE Vernova", "Industrials", 130, 470.0),
    ("TJX", "TJX Companies", "Consumer Discretionary", 130, 115.0),
    ("PANW", "Palo Alto Networks", "Technology", 125, 190.0),
    ("COP", "ConocoPhillips", "Energy", 125, 105.0),
    ("ADI", "Analog Devices", "Technology", 110, 225.0),
    ("DE", "Deere & Co", "Industrials", 115, 425.0),
    ("BX", "Blackstone", "Financials", 115, 155.0),
    ("MDT", "Medtronic", "Health Care", 115, 90.0),
    ("IBN", "ICICI Bank ADR", "Financials", 115, 32.0),
    ("UBS", "UBS Group", "Financials", 115, 36.0),
    ("SE", "Sea Limited ADR", "Consumer Discretionary", 110, 185.0),
    ("LMT", "Lockheed Martin", "Industrials", 110, 465.0),
    ("CB", "Chubb", "Financials", 110, 275.0),
    ("ENB", "Enbridge", "Energy", 105, 48.0),
    ("RIO", "Rio Tinto ADR", "Materials", 105, 65.0),
    ("DASH", "DoorDash", "Consumer Discretionary", 105, 250.0),
    ("KKR", "KKR & Co", "Financials", 105, 120.0),
    ("MMC", "Marsh & McLennan", "Financials", 105, 215.0),
    ("PLD", "Prologis", "Real Estate", 105, 112.0),
    ("FI", "Fiserv", "Financials", 105, 185.0),
    ("GILD", "Gilead Sciences", "Health Care", 105, 85.0),
    ("SBUX", "Starbucks", "Consumer Discretionary", 105, 92.0),
    ("LRCX", "Lam Research", "Technology", 105, 80.0),
    ("BMY", "Bristol-Myers Squibb", "Health Care", 100, 50.0),
    ("SO", "Southern Company", "Utilities", 100, 90.0),
    ("KLAC", "KLA Corp", "Technology", 100, 750.0),
    ("SMFG", "Sumitomo Mitsui Financial ADR", "Financials", 100, 17.0),
    ("NKE", "Nike", "Consumer Discretionary", 95, 65.0),
    ("ICE", "Intercontinental Exchange", "Financials", 95, 165.0),
    ("AMT", "American Tower", "Real Estate", 95, 205.0),
    ("HCA", "HCA Healthcare", "Health Care", 95, 390.0),
    ("BTI", "British American Tobacco ADR", "Consumer Staples", 95, 43.0),
    ("GSK", "GSK ADR", "Health Care", 95, 46.0),
    ("CRWD", "CrowdStrike", "Technology", 90, 360.0),
    ("SCCO", "Southern Copper", "Materials", 90, 115.0),
    ("CEG", "Constellation Energy", "Utilities", 90, 285.0),
    ("WELL", "Welltower", "Real Estate", 90, 145.0),
    ("DUK", "Duke Energy", "Utilities", 90, 117.0),
    ("SHW", "Sherwin-Williams", "Materials", 90, 360.0),
    ("CME", "CME Group", "Financials", 90, 250.0),
    ("APH", "Amphenol", "Technology", 90, 75.0),
    ("DELL", "Dell Technologies", "Technology", 90, 130.0),
    ("COIN", "Coinbase Global", "Financials", 90, 350.0),
    ("HOOD", "Robinhood Markets", "Financials", 90, 100.0),
    ("BP", "BP ADR", "Energy", 90, 34.0),
    ("BBVA", "Banco Bilbao Vizcaya ADR", "Financials", 90, 16.0),
    ("NTES", "NetEase ADR", "Communication Services", 90, 140.0),
    ("MSTR", "Strategy Inc", "Technology", 90, 330.0),
    ("RELX", "RELX ADR", "Industrials", 90, 48.0),
    ("MCO", "Moody's", "Financials", 85, 470.0),
    ("APO", "Apollo Global Management", "Financials", 85, 145.0),
    ("ELV", "Elevance Health", "Health Care", 85, 370.0),
    ("MO", "Altria Group", "Consumer Staples", 85, 50.0),
    ("CI", "Cigna Group", "Health Care", 85, 305.0),
    ("WM", "Waste Management", "Industrials", 85, 210.0),
    ("PH", "Parker-Hannifin", "Industrials", 85, 655.0),
    ("MCK", "McKesson", "Health Care", 85, 670.0),
    ("CDNS", "Cadence Design Systems", "Technology", 85, 310.0),
    ("TT", "Trane Technologies", "Industrials", 85, 380.0),
    ("COF", "Capital One Financial", "Financials", 85, 215.0),
    ("MMM", "3M", "Industrials", 85, 155.0),
    ("PBR", "Petroleo Brasileiro ADR", "Energy", 85, 13.0),
    ("BMO", "Bank of Montreal", "Financials", 85, 115.0),
    ("SNPS", "Synopsys", "Technology", 80, 520.0),
    ("CVS", "CVS Health", "Health Care", 80, 63.0),
    ("EQIX", "Equinix", "Real Estate", 80, 830.0),
    ("MDLZ", "Mondelez International", "Consumer Staples", 80, 60.0),
    ("GD", "General Dynamics", "Industrials", 80, 295.0),
    ("ABNB", "Airbnb", "Consumer Discretionary", 80, 130.0),
    ("CTAS", "Cintas", "Industrials", 80, 200.0),
    ("ZTS", "Zoetis", "Health Care", 75, 165.0),
    ("CL", "Colgate-Palmolive", "Consumer Staples", 75, 92.0),
    ("MSI", "Motorola Solutions", "Technology", 75, 445.0),
    ("ITW", "Illinois Tool Works", "Industrials", 75, 250.0),
    ("NOC", "Northrop Grumman", "Industrials", 75, 520.0),
    ("AON", "Aon", "Financials", 75, 345.0),
    ("SNOW", "Snowflake", "Technology", 75, 225.0),
    ("FTNT", "Fortinet", "Technology", 75, 98.0),
    ("MRVL", "Marvell Technology", "Technology", 75, 88.0),
    ("TDG", "TransDigm Group", "Industrials", 75, 1330.0),
    ("BK", "Bank of New York Mellon", "Financials", 75, 105.0),
    ("UPS", "United Parcel Service", "Industrials", 75, 88.0),
    ("NU", "Nu Holdings", "Financials", 75, 15.0),
    ("BNS", "Bank of Nova Scotia", "Financials", 75, 60.0),
    ("INFY", "Infosys ADR", "Technology", 75, 18.0),
    ("CVNA", "Carvana", "Consumer Discretionary", 70, 330.0),
    ("CRWV", "CoreWeave", "Technology", 70, 140.0),
    ("EPD", "Enterprise Products Partners", "Energy", 70, 32.0),
    ("CRH", "CRH plc", "Materials", 70, 100.0),
    ("AEM", "Agnico Eagle Mines", "Materials", 70, 140.0),
    ("RSG", "Republic Services", "Industrials", 70, 225.0),
    ("ORLY", "O'Reilly Automotive", "Consumer Discretionary", 70, 98.0),
    ("USB", "U.S. Bancorp", "Financials", 70, 45.0),
    ("PNC", "PNC Financial Services", "Financials", 70, 175.0),
    ("APD", "Air Products & Chemicals", "Materials", 70, 290.0),
    ("MAR", "Marriott International", "Consumer Discretionary", 70, 255.0),
    ("ECL", "Ecolab", "Materials", 70, 245.0),
    ("EMR", "Emerson Electric", "Industrials", 70, 125.0),
    ("AJG", "Arthur J. Gallagher", "Financials", 70, 320.0),
    ("RCL", "Royal Caribbean Cruises", "Consumer Discretionary", 70, 260.0),
    ("NET", "Cloudflare", "Technology", 70, 200.0),
    ("RBLX", "Roblox", "Communication Services", 70, 105.0),
    ("WDAY", "Workday", "Technology", 65, 240.0),
    ("ADSK", "Autodesk", "Technology", 65, 300.0),
    ("JCI", "Johnson Controls International", "Industrials", 65, 100.0),
    ("EOG", "EOG Resources", "Energy", 65, 118.0),
    ("WMB", "Williams Companies", "Energy", 65, 53.0),
    ("NEM", "Newmont", "Materials", 65, 58.0),
    ("EQNR", "Equinor ADR", "Energy", 65, 24.0),
    ("CNQ", "Canadian Natural Resources", "Energy", 65, 32.0),
    ("DB", "Deutsche Bank", "Financials", 65, 33.0),
    ("BCS", "Barclays ADR", "Financials", 65, 22.0),
    ("ING", "ING Groep ADR", "Financials", 65, 22.0),
    ("MFG", "Mizuho Financial ADR", "Financials", 65, 6.0),
    ("CM", "Canadian Imperial Bank of Commerce", "Financials", 65, 70.0),
    ("GM", "General Motors", "Consumer Discretionary", 60, 62.0),
    ("MNST", "Monster Beverage", "Consumer Staples", 60, 62.0),
    ("DEO", "Diageo ADR", "Consumer Staples", 60, 105.0),
    ("ET", "Energy Transfer", "Energy", 60, 17.0),
    ("REGN", "Regeneron Pharmaceuticals", "Health Care", 60, 550.0),
    ("COR", "Cencora", "Health Care", 60, 310.0),
    ("SPG", "Simon Property Group", "Real Estate", 60, 180.0),
    ("DLR", "Digital Realty Trust", "Real Estate", 60, 175.0),
    ("AZO", "AutoZone", "Consumer Discretionary", 60, 3600.0),
    ("FCX", "Freeport-McMoRan", "Materials", 60, 42.0),
    ("TRV", "Travelers Companies", "Financials", 60, 260.0),
    ("KMI", "Kinder Morgan", "Energy", 60, 27.0),
    ("CSX", "CSX Corp", "Industrials", 60, 32.0),
    ("TFC", "Truist Financial", "Financials", 60, 45.0),
    ("NSC", "Norfolk Southern", "Industrials", 60, 265.0),
    ("CMG", "Chipotle Mexican Grill", "Consumer Discretionary", 60, 45.0),
    ("HWM", "Howmet Aerospace", "Industrials", 60, 150.0),
    ("AXON", "Axon Enterprise", "Industrials", 55, 700.0),
    ("TEAM", "Atlassian", "Technology", 55, 210.0),
    ("ALNY", "Alnylam Pharmaceuticals", "Health Care", 55, 420.0),
    ("EA", "Electronic Arts", "Communication Services", 55, 205.0),
    ("LNG", "Cheniere Energy", "Energy", 55, 245.0),
    ("MPLX", "MPLX LP", "Energy", 55, 53.0),
    ("TRP", "TC Energy", "Energy", 55, 53.0),
    ("MPC", "Marathon Petroleum", "Energy", 55, 175.0),
    ("AEP", "American Electric Power", "Utilities", 55, 105.0),
    ("SRE", "Sempra", "Utilities", 55, 85.0),
    ("VST", "Vistra", "Utilities", 55, 160.0),
    ("ARES", "Ares Management", "Financials", 55, 170.0),
    ("MET", "MetLife", "Financials", 55, 82.0),
    ("AFL", "Aflac", "Financials", 55, 105.0),
    ("ALL", "Allstate", "Financials", 55, 205.0),
    ("PSA", "Public Storage", "Real Estate", 55, 310.0),
    ("HLT", "Hilton Worldwide", "Consumer Discretionary", 55, 230.0),
    ("CMI", "Cummins", "Industrials", 55, 400.0),
    ("PWR", "Quanta Services", "Industrials", 55, 375.0),
    ("ROP", "Roper Technologies", "Technology", 55, 510.0),
    ("NXPI", "NXP Semiconductors", "Technology", 55, 215.0),
    ("TEL", "TE Connectivity", "Technology", 55, 185.0),
    ("GLW", "Corning", "Technology", 55, 65.0),
    ("MFC", "Manulife Financial", "Financials", 55, 32.0),
    ("KR", "Kroger", "Consumer Staples", 45, 68.0),
    ("SLB", "SLB", "Energy", 50, 36.0),
    ("D", "Dominion Energy", "Utilities", 50, 58.0),
    ("SU", "Suncor Energy", "Energy", 50, 40.0),
    ("E", "Eni ADR", "Energy", 50, 32.0),
    ("OKE", "ONEOK", "Energy", 50, 85.0),
    ("PSX", "Phillips 66", "Energy", 50, 125.0),
    ("F", "Ford Motor", "Consumer Discretionary", 50, 12.0),
    ("O", "Realty Income", "Real Estate", 50, 57.0),
    ("GOLD", "Barrick Mining", "Materials", 50, 28.0),
    ("DDOG", "Datadog", "Technology", 50, 145.0),
    ("ROST", "Ross Stores", "Consumer Discretionary", 50, 155.0),
    ("FAST", "Fastenal", "Industrials", 50, 88.0),
    ("PAYX", "Paychex", "Industrials", 50, 140.0),
    ("LHX", "L3Harris Technologies", "Industrials", 50, 265.0),
    ("GWW", "W.W. Grainger", "Industrials", 50, 1030.0),
    ("BDX", "Becton Dickinson", "Health Care", 50, 175.0),
    ("AMP", "Ameriprise Financial", "Financials", 48, 500.0),
    ("EBAY", "eBay", "Consumer Discretionary", 40, 85.0),
    ("AIG", "American International Group", "Financials", 45, 80.0),
    ("OXY", "Occidental Petroleum", "Energy", 45, 48.0),
    ("FANG", "Diamondback Energy", "Energy", 45, 155.0),
    ("BKR", "Baker Hughes", "Energy", 45, 45.0),
    ("WPM", "Wheaton Precious Metals", "Materials", 45, 100.0),
    ("VALE", "Vale ADR", "Materials", 45, 10.0),
    ("XEL", "Xcel Energy", "Utilities", 45, 78.0),
    ("EXC", "Exelon", "Utilities", 45, 45.0),
    ("KDP", "Keurig Dr Pepper", "Consumer Staples", 45, 33.0),
    ("VEEV", "Veeva Systems", "Technology", 45, 275.0),
    ("EW", "Edwards Lifesciences", "Health Care", 45, 75.0),
    ("IDXX", "IDEXX Laboratories", "Health Care", 45, 550.0),
    ("TCOM", "Trip.com Group ADR", "Consumer Discretionary", 45, 68.0),
    ("JD", "JD.com ADR", "Consumer Discretionary", 45, 32.0),
    ("HMC", "Honda Motor ADR", "Consumer Discretionary", 45, 30.0),
    ("MSCI", "MSCI", "Financials", 45, 570.0),
    ("FICO", "Fair Isaac", "Technology", 45, 1800.0),
    ("NDAQ", "Nasdaq", "Financials", 45, 78.0),
    ("CBRE", "CBRE Group", "Real Estate", 45, 145.0),
    ("WCN", "Waste Connections", "Industrials", 45, 175.0),
    ("URI", "United Rentals", "Industrials", 45, 690.0),
    ("GRMN", "Garmin", "Technology", 45, 230.0),
    ("TGT", "Target", "Consumer Discretionary", 45, 98.0),
    ("KMB", "Kimberly-Clark", "Consumer Staples", 42, 128.0),
    ("CTVA", "Corteva", "Materials", 42, 62.0),
    ("DHI", "D.R. Horton", "Consumer Discretionary", 42, 140.0),
    ("SYY", "Sysco", "Consumer Staples", 37, 76.0),
    ("VLO", "Valero Energy", "Energy", 40, 130.0),
    ("TRGP", "Targa Resources", "Energy", 40, 185.0),
    ("IMO", "Imperial Oil", "Energy", 40, 80.0),
    ("ETR", "Entergy", "Utilities", 40, 92.0),
    ("PEG", "Public Service Enterprise Group", "Utilities", 40, 80.0),
    ("PCG", "PG&E", "Utilities", 40, 18.0),
    ("CCI", "Crown Castle", "Real Estate", 40, 92.0),
    ("SLF", "Sun Life Financial", "Financials", 40, 70.0),
    ("FIS", "Fidelity National Information", "Financials", 40, 75.0),
    ("CRCL", "Circle Internet Group", "Financials", 40, 170.0),
    ("RDDT", "Reddit", "Communication Services", 40, 210.0),
    ("ZS", "Zscaler", "Technology", 40, 260.0),
    ("YUM", "Yum! Brands", "Consumer Discretionary", 40, 145.0),
    ("CAH", "Cardinal Health", "Health Care", 40, 170.0),
    ("RMD", "ResMed", "Health Care", 40, 275.0),
    ("AME", "AMETEK", "Industrials", 40, 175.0),
    ("ROK", "Rockwell Automation", "Industrials", 40, 350.0),
    ("VRSK", "Verisk Analytics", "Industrials", 40, 280.0),
    ("PRU", "Prudential Financial", "Financials", 38, 108.0),
    ("VMC", "Vulcan Materials", "Materials", 38, 290.0),
    ("STX", "Seagate Technology", "Technology", 35, 165.0),
    ("CTSH", "Cognizant Technology Solutions", "Technology", 35, 72.0),
    ("MCHP", "Microchip Technology", "Technology", 35, 65.0),
    ("MPWR", "Monolithic Power Systems", "Technology", 35, 730.0),
    ("KEYS", "Keysight Technologies", "Technology", 30, 175.0),
    ("EQT", "EQT Corp", "Energy", 35, 58.0),
    ("CCJ", "Cameco", "Energy", 35, 80.0),
    ("MLM", "Martin Marietta Materials", "Materials", 35, 570.0),
    ("FMX", "Fomento Economico Mexicano ADR", "Consumer Staples", 35, 100.0),
    ("HSY", "Hershey", "Consumer Staples", 35, 175.0),
    ("EXR", "Extra Space Storage", "Real Estate", 33, 155.0),
    ("VICI", "VICI Properties", "Real Estate", 33, 31.0),
    ("MTB", "M&T Bank", "Financials", 33, 200.0),
    ("ACGL", "Arch Capital Group", "Financials", 33, 88.0),
    ("WAB", "Westinghouse Air Brake", "Industrials", 33, 195.0),
    ("IQV", "IQVIA Holdings", "Health Care", 35, 200.0),
    ("A", "Agilent Technologies", "Health Care", 35, 122.0),
    ("GEHC", "GE HealthCare Technologies", "Health Care", 35, 78.0),
    ("HEI", "HEICO", "Industrials", 35, 255.0),
    ("LYV", "Live Nation Entertainment", "Communication Services", 35, 150.0),
    ("CHTR", "Charter Communications", "Communication Services", 35, 250.0),
    ("BIDU", "Baidu ADR", "Communication Services", 35, 100.0),
    ("CCL", "Carnival", "Consumer Discretionary", 35, 28.0),
    ("DAL", "Delta Air Lines", "Industrials", 35, 55.0),
    ("HIG", "Hartford Insurance Group", "Financials", 35, 125.0),
    ("CSGP", "CoStar Group", "Real Estate", 32, 78.0),
    ("KHC", "Kraft Heinz", "Consumer Staples", 32, 27.0),
    ("LVS", "Las Vegas Sands", "Consumer Discretionary", 32, 48.0),
    ("NUE", "Nucor", "Materials", 32, 140.0),
    ("RJF", "Raymond James Financial", "Financials", 32, 160.0),
    ("WTW", "Willis Towers Watson", "Financials", 32, 330.0),
    ("UAL", "United Airlines Holdings", "Industrials", 32, 95.0),
    ("IR", "Ingersoll Rand", "Industrials", 35, 85.0),
    ("EFX", "Equifax", "Industrials", 30, 240.0),
    ("DD", "DuPont de Nemours", "Materials", 30, 72.0),
    ("EL", "Estee Lauder", "Consumer Staples", 30, 85.0),
    ("GIS", "General Mills", "Consumer Staples", 30, 55.0),
    ("STZ", "Constellation Brands", "Consumer Staples", 30, 170.0),
    ("IRM", "Iron Mountain", "Real Estate", 30, 100.0),
    ("STT", "State Street", "Financials", 30, 105.0),
    ("FITB", "Fifth Third Bancorp", "Financials", 30, 45.0),
    ("SOFI", "SoFi Technologies", "Financials", 30, 25.0),
    ("LPLA", "LPL Financial Holdings", "Financials", 30, 400.0),
    ("IBKR", "Interactive Brokers Group", "Financials", 30, 65.0),
    ("BRO", "Brown & Brown", "Financials", 30, 105.0),
    ("TTD", "Trade Desk", "Technology", 30, 60.0),
    ("HUBS", "HubSpot", "Technology", 30, 580.0),
    ("WDC", "Western Digital", "Technology", 30, 85.0),
    ("HPE", "Hewlett Packard Enterprise", "Technology", 30, 22.0),
    ("NOK", "Nokia ADR", "Technology", 30, 5.5),
    ("WIT", "Wipro ADR", "Technology", 30, 3.0),
    ("FIG", "Figma", "Technology", 30, 60.0),
    ("HUM", "Humana", "Health Care", 30, 250.0),
    ("DXCM", "DexCom", "Health Care", 30, 78.0),
    ("LEN", "Lennar", "Consumer Discretionary", 30, 115.0),
    ("QSR", "Restaurant Brands International", "Consumer Discretionary", 30, 66.0),
    ("NRG", "NRG Energy", "Utilities", 30, 145.0),
    ("ERIC", "Ericsson ADR", "Technology", 28, 8.5),
    ("SYF", "Synchrony Financial", "Financials", 28, 75.0),
    ("WRB", "W. R. Berkley", "Financials", 28, 74.0),
    ("BR", "Broadridge Financial Solutions", "Technology", 28, 240.0),
    ("TSCO", "Tractor Supply", "Consumer Discretionary", 28, 52.0),
    ("EXPE", "Expedia Group", "Consumer Discretionary", 28, 220.0),
    ("AVB", "AvalonBay Communities", "Real Estate", 28, 195.0),
    ("DTE", "DTE Energy", "Utilities", 27, 132.0),
    ("AEE", "Ameren", "Utilities", 27, 100.0),
    ("PPL", "PPL Corp", "Utilities", 27, 36.0),
    ("K", "Kellanova", "Consumer Staples", 27, 80.0),
    ("HBAN", "Huntington Bancshares", "Financials", 27, 18.0),
    ("VTR", "Ventas", "Real Estate", 27, 63.0),
    ("EQR", "Equity Residential", "Real Estate", 26, 68.0),
    ("ADM", "Archer-Daniels-Midland", "Consumer Staples", 25, 52.0),
    ("DG", "Dollar General", "Consumer Staples", 25, 115.0),
    ("IP", "International Paper", "Materials", 25, 48.0),
    ("PPG", "PPG Industries", "Materials", 25, 110.0),
    ("KGC", "Kinross Gold", "Materials", 25, 20.0),
    ("ASX", "ASE Technology ADR", "Technology", 25, 11.0),
    ("ON", "ON Semiconductor", "Technology", 25, 58.0),
    ("TER", "Teradyne", "Technology", 25, 155.0),
    ("SMCI", "Super Micro Computer", "Technology", 25, 42.0),
    ("MDB", "MongoDB", "Technology", 25, 300.0),
    ("ZM", "Zoom Communications", "Technology", 25, 82.0),
    ("PSTG", "Pure Storage", "Technology", 25, 75.0),
    ("VRSN", "VeriSign", "Technology", 25, 270.0),
    ("CBOE", "Cboe Global Markets", "Financials", 25, 240.0),
    ("NTRS", "Northern Trust", "Financials", 25, 130.0),
    ("TROW", "T. Rowe Price Group", "Financials", 25, 115.0),
    ("CINF", "Cincinnati Financial", "Financials", 25, 160.0),
    ("MKL", "Markel Group", "Financials", 25, 2000.0),
    ("AFRM", "Affirm Holdings", "Financials", 25, 78.0),
    ("CPAY", "Corpay", "Technology", 22, 320.0),
    ("EME", "EMCOR Group", "Industrials", 25, 560.0),
    ("FIX", "Comfort Systems USA", "Industrials", 25, 700.0),
    ("TDY", "Teledyne Technologies", "Industrials", 25, 530.0),
    ("VLTO", "Veralto", "Industrials", 25, 100.0),
    ("STE", "STERIS", "Health Care", 25, 255.0),
    ("MTD", "Mettler-Toledo International", "Health Care", 25, 1200.0),
    ("PODD", "Insulet", "Health Care", 25, 350.0),
    ("BNTX", "BioNTech ADR", "Health Care", 25, 105.0),
    ("COHR", "Coherent", "Technology", 25, 155.0),
    ("ALAB", "Astera Labs", "Technology", 25, 150.0),
    ("FOXA", "Fox Corp Class A", "Communication Services", 25, 55.0),
    ("PINS", "Pinterest", "Communication Services", 25, 37.0),
    ("ULTA", "Ulta Beauty", "Consumer Discretionary", 22, 490.0),
    ("WSM", "Williams-Sonoma", "Consumer Discretionary", 22, 180.0),
    ("TPR", "Tapestry", "Consumer Discretionary", 22, 105.0),
    ("PHM", "PulteGroup", "Consumer Discretionary", 22, 115.0),
    ("NVR", "NVR", "Consumer Discretionary", 22, 7500.0),
    ("DLTR", "Dollar Tree", "Consumer Staples", 21, 105.0),
    ("CHD", "Church & Dwight", "Consumer Staples", 22, 90.0),
    ("DVN", "Devon Energy", "Energy", 22, 35.0),
    ("CTRA", "Coterra Energy", "Energy", 20, 26.0),
    ("HAL", "Halliburton", "Energy", 20, 24.0),
    ("DOW", "Dow Inc", "Materials", 22, 31.0),
    ("STLD", "Steel Dynamics", "Materials", 22, 145.0),
    ("SW", "Smurfit Westrock", "Materials", 22, 42.0),
    ("CMS", "CMS Energy", "Utilities", 22, 73.0),
    ("ATO", "Atmos Energy", "Utilities", 25, 155.0),
    ("LH", "Labcorp Holdings", "Health Care", 22, 265.0),
    ("TEVA", "Teva Pharmaceutical ADR", "Health Care", 22, 19.0),
    ("CHKP", "Check Point Software", "Technology", 22, 200.0),
    ("NTNX", "Nutanix", "Technology", 22, 80.0),
    ("NTAP", "NetApp", "Technology", 22, 110.0),
    ("CRDO", "Credo Technology", "Technology", 22, 130.0),
    ("PTC", "PTC Inc", "Technology", 22, 185.0),
    ("SSNC", "SS&C Technologies", "Technology", 22, 85.0),
    ("HUBB", "Hubbell", "Industrials", 22, 415.0),
    ("LDOS", "Leidos Holdings", "Industrials", 22, 175.0),
    ("TXT", "Textron", "Industrials", 14, 80.0),
    ("GRAB", "Grab Holdings", "Industrials", 22, 5.5),
    ("CFG", "Citizens Financial Group", "Financials", 22, 50.0),
    ("DGX", "Quest Diagnostics", "Health Care", 21, 190.0),
    ("TECK", "Teck Resources", "Materials", 20, 40.0),
    ("LYB", "LyondellBasell Industries", "Materials", 20, 62.0),
    ("IFF", "International Flavors & Fragrances", "Materials", 20, 78.0),
    ("LII", "Lennox International", "Industrials", 20, 570.0),
    ("EIX", "Edison International", "Utilities", 20, 52.0),
    ("NI", "NiSource", "Utilities", 20, 42.0),
    ("KEY", "KeyCorp", "Financials", 20, 19.0),
    ("L", "Loews", "Financials", 20, 95.0),
    ("CYBR", "CyberArk Software", "Technology", 20, 400.0),
    ("TWLO", "Twilio", "Technology", 20, 125.0),
    ("GFS", "GlobalFoundries", "Technology", 20, 36.0),
    ("TOST", "Toast", "Technology", 20, 35.0),
    ("GPN", "Global Payments", "Financials", 20, 80.0),
    ("BIIB", "Biogen", "Health Care", 20, 140.0),
    ("ZBH", "Zimmer Biomet Holdings", "Health Care", 20, 100.0),
    ("WAT", "Waters", "Health Care", 20, 340.0),
    ("DKNG", "DraftKings", "Consumer Discretionary", 20, 40.0),
    ("LULU", "Lululemon Athletica", "Consumer Discretionary", 20, 175.0),
    ("INVH", "Invitation Homes", "Real Estate", 20, 33.0),
    ("WY", "Weyerhaeuser", "Real Estate", 20, 28.0),
    ("PARA", "Paramount Skydance", "Communication Services", 20, 15.0),
    ("RKLB", "Rocket Lab", "Industrials", 20, 40.0),
    ("PKG", "Packaging Corp of America", "Materials", 19, 210.0),
    ("MKC", "McCormick", "Consumer Staples", 19, 71.0),
    ("LUV", "Southwest Airlines", "Industrials", 18, 32.0),
    ("Z", "Zillow Group", "Real Estate", 18, 72.0),
    ("ESS", "Essex Property Trust", "Real Estate", 18, 275.0),
    ("TRMB", "Trimble", "Technology", 18, 75.0),
    ("U", "Unity Software", "Technology", 18, 42.0),
    ("OKTA", "Okta", "Technology", 18, 100.0),
    ("UMC", "United Microelectronics ADR", "Technology", 18, 7.5),
    ("UTHR", "United Therapeutics", "Health Care", 18, 390.0),
    ("INCY", "Incyte", "Health Care", 18, 95.0),
    ("RL", "Ralph Lauren", "Consumer Discretionary", 18, 290.0),
    ("CHWY", "Chewy", "Consumer Discretionary", 18, 42.0),
    ("BURL", "Burlington Stores", "Consumer Discretionary", 18, 285.0),
    ("CASY", "Casey's General Stores", "Consumer Staples", 18, 480.0),
    ("ASTS", "AST SpaceMobile", "Communication Services", 18, 55.0),
    ("RIVN", "Rivian Automotive", "Consumer Discretionary", 18, 15.0),
    ("ERIE", "Erie Indemnity", "Financials", 17, 330.0),
    ("TRU", "TransUnion", "Financials", 17, 88.0),
    ("SNA", "Snap-on", "Industrials", 17, 330.0),
    ("CW", "Curtiss-Wright", "Industrials", 17, 450.0),
    ("FTV", "Fortive", "Industrials", 17, 50.0),
    ("PNR", "Pentair", "Industrials", 17, 105.0),
    ("LNT", "Alliant Energy", "Utilities", 17, 65.0),
    ("MAA", "Mid-America Apartment Communities", "Real Estate", 17, 145.0),
    ("EXPD", "Expeditors International", "Industrials", 16, 120.0),
    ("DT", "Dynatrace", "Technology", 16, 52.0),
    ("FFIV", "F5 Inc", "Technology", 16, 280.0),
    ("HRL", "Hormel Foods", "Consumer Staples", 16, 29.0),
    ("WSO", "Watsco", "Industrials", 16, 420.0),
    ("J", "Jacobs Solutions", "Industrials", 16, 135.0),
    ("EVRG", "Evergy", "Utilities", 16, 70.0),
    ("CLX", "Clorox", "Consumer Staples", 15, 120.0),
    ("BBY", "Best Buy", "Consumer Discretionary", 15, 72.0),
    ("MAS", "Masco", "Industrials", 15, 70.0),
    ("XPO", "XPO Inc", "Industrials", 15, 125.0),
    ("AECOM", "AECOM", "Industrials", 15, 115.0),
    ("BWXT", "BWX Technologies", "Industrials", 15, 160.0),
    ("NXT", "Nextracker", "Industrials", 9, 60.0),
    ("KIM", "Kimco Realty", "Real Estate", 15, 22.0),
    ("AMCR", "Amcor", "Materials", 15, 10.0),
    ("BALL", "Ball Corp", "Materials", 15, 52.0),
    ("RPM", "RPM International", "Materials", 15, 115.0),
    ("APTV", "Aptiv", "Consumer Discretionary", 15, 75.0),
    ("DECK", "Deckers Outdoor", "Consumer Discretionary", 15, 100.0),
    ("ONON", "On Holding", "Consumer Discretionary", 15, 45.0),
    ("DPZ", "Domino's Pizza", "Consumer Discretionary", 15, 440.0),
    ("SNAP", "Snap Inc", "Communication Services", 15, 9.0),
    ("OMC", "Omnicom Group", "Communication Services", 15, 78.0),
    ("EXAS", "Exact Sciences", "Health Care", 15, 80.0),
    ("HOLX", "Hologic", "Health Care", 15, 68.0),
    ("CNC", "Centene", "Health Care", 15, 30.0),
    ("COO", "Cooper Companies", "Health Care", 15, 75.0),
    ("IT", "Gartner", "Technology", 25, 320.0),
    ("FDS", "FactSet Research Systems", "Financials", 15, 400.0),
    ("EG", "Everest Group", "Financials", 14, 340.0),
    ("CHRW", "C.H. Robinson Worldwide", "Industrials", 14, 120.0),
    ("JBHT", "J.B. Hunt Transport Services", "Industrials", 14, 145.0),
    ("GGG", "Graco", "Industrials", 14, 85.0),
    ("CF", "CF Industries Holdings", "Materials", 14, 85.0),
    ("ROKU", "Roku", "Communication Services", 14, 95.0),
    ("TKO", "TKO Group Holdings", "Communication Services", 14, 170.0),
    ("NBIX", "Neurocrine Biosciences", "Health Care", 14, 140.0),
    ("SOLV", "Solventum", "Health Care", 14, 80.0),
    ("WAL", "Western Alliance Bancorporation", "Financials", 10, 90.0),
    ("WPC", "W. P. Carey", "Real Estate", 14, 63.0),
    ("TYL", "Tyler Technologies", "Technology", 24, 560.0),
    ("BLD", "TopBuild", "Industrials", 10, 340.0),
    ("BLDR", "Builders FirstSource", "Industrials", 13, 115.0),
    ("UDR", "UDR Inc", "Real Estate", 13, 40.0),
    ("ARE", "Alexandria Real Estate Equities", "Real Estate", 13, 75.0),
    ("REG", "Regency Centers", "Real Estate", 13, 72.0),
    ("AMH", "American Homes 4 Rent", "Real Estate", 13, 35.0),
    ("JLL", "Jones Lang LaSalle", "Real Estate", 13, 275.0),
    ("PAA", "Plains All American Pipeline", "Energy", 13, 18.0),
    ("AVY", "Avery Dennison", "Materials", 13, 165.0),
    ("IONQ", "IonQ", "Technology", 12, 45.0),
    ("ESTC", "Elastic", "Technology", 9, 85.0),
    ("MNDY", "monday.com", "Technology", 12, 235.0),
    ("PAYC", "Paycom Software", "Technology", 12, 215.0),
    ("JKHY", "Jack Henry & Associates", "Technology", 12, 165.0),
    ("AKAM", "Akamai Technologies", "Technology", 12, 80.0),
    ("LITE", "Lumentum Holdings", "Technology", 12, 165.0),
    ("FN", "Fabrinet", "Technology", 12, 330.0),
    ("ENTG", "Entegris", "Technology", 15, 100.0),
    ("IREN", "IREN Ltd", "Technology", 12, 45.0),
    ("BEN", "Franklin Resources", "Financials", 12, 23.0),
    ("MORN", "Morningstar", "Financials", 12, 285.0),
    ("RNR", "RenaissanceRe Holdings", "Financials", 12, 240.0),
    ("BAX", "Baxter International", "Health Care", 12, 24.0),
    ("BMRN", "BioMarin Pharmaceutical", "Health Care", 12, 62.0),
    ("MRNA", "Moderna", "Health Care", 12, 30.0),
    ("ALGN", "Align Technology", "Health Care", 12, 165.0),
    ("DOCS", "Doximity", "Health Care", 12, 62.0),
    ("TEM", "Tempus AI", "Health Care", 12, 70.0),
    ("OKLO", "Oklo", "Utilities", 12, 85.0),
    ("BE", "Bloom Energy", "Industrials", 12, 50.0),
    ("NDSN", "Nordson", "Industrials", 12, 210.0),
    ("BAH", "Booz Allen Hamilton", "Industrials", 12, 95.0),
    ("NVT", "nVent Electric", "Industrials", 12, 75.0),
    ("OC", "Owens Corning", "Industrials", 12, 140.0),
    ("CPT", "Camden Property Trust", "Real Estate", 12, 110.0),
    ("BXP", "BXP Inc", "Real Estate", 12, 70.0),
    ("OHI", "Omega Healthcare Investors", "Real Estate", 12, 40.0),
    ("CCK", "Crown Holdings", "Materials", 12, 105.0),
    ("RGLD", "Royal Gold", "Materials", 12, 180.0),
    ("WYNN", "Wynn Resorts", "Consumer Discretionary", 12, 115.0),
    ("TOL", "Toll Brothers", "Consumer Discretionary", 12, 125.0),
    ("POOL", "Pool Corp", "Consumer Discretionary", 12, 320.0),
    ("SWKS", "Skyworks Solutions", "Technology", 12, 78.0),
    ("CIEN", "Ciena", "Technology", 14, 95.0),
    ("SWK", "Stanley Black & Decker", "Industrials", 11, 70.0),
    ("SJM", "J.M. Smucker", "Consumer Staples", 11, 105.0),
    ("ACI", "Albertsons Companies", "Consumer Staples", 11, 19.0),
    ("VTRS", "Viatris", "Health Care", 11, 9.0),
    ("CACI", "CACI International", "Industrials", 11, 490.0),
    ("HST", "Host Hotels & Resorts", "Real Estate", 11, 16.0),
    ("GL", "Globe Life", "Financials", 11, 135.0),
    ("AIZ", "Assurant", "Financials", 10, 200.0),
    ("CAG", "Conagra Brands", "Consumer Staples", 10, 21.0),
    ("CPB", "Campbell's Co", "Consumer Staples", 10, 33.0),
    ("IVZ", "Invesco", "Financials", 10, 22.0),
    ("GLXY", "Galaxy Digital", "Financials", 10, 25.0),
    ("MOH", "Molina Healthcare", "Health Care", 10, 180.0),
    ("HIMS", "Hims & Hers Health", "Health Care", 10, 45.0),
    ("SMR", "NuScale Power", "Utilities", 10, 38.0),
    ("ALB", "Albemarle", "Materials", 10, 85.0),
    ("W", "Wayfair", "Consumer Discretionary", 10, 80.0),
    ("HAS", "Hasbro", "Consumer Discretionary", 10, 72.0),
    ("NCLH", "Norwegian Cruise Line Holdings", "Consumer Discretionary", 10, 22.0),
    ("MGM", "MGM Resorts International", "Consumer Discretionary", 9, 35.0),
    ("CUBE", "CubeSmart", "Real Estate", 9, 40.0),
    ("EGP", "EastGroup Properties", "Real Estate", 9, 175.0),
    ("AOS", "A.O. Smith", "Industrials", 9, 65.0),
    ("JOBY", "Joby Aviation", "Industrials", 9, 12.0),
    ("EMN", "Eastman Chemical", "Materials", 9, 78.0),
    ("MOS", "Mosaic", "Materials", 8, 26.0),
    ("AES", "AES Corp", "Utilities", 9, 13.0),
    ("CAVA", "CAVA Group", "Consumer Discretionary", 9, 75.0),
    ("NYT", "New York Times", "Communication Services", 9, 55.0),
    ("IPG", "Interpublic Group", "Communication Services", 9, 25.0),
    ("MASI", "Masimo", "Health Care", 9, 165.0),
    ("ZION", "Zions Bancorporation", "Financials", 8, 55.0),
    ("CMA", "Comerica", "Financials", 9, 68.0),
    ("DBX", "Dropbox", "Technology", 8, 28.0),
    ("GTLB", "GitLab", "Technology", 8, 48.0),
    ("CFLT", "Confluent", "Technology", 8, 25.0),
    ("WIX", "Wix.com", "Technology", 8, 145.0),
    ("QBTS", "D-Wave Quantum", "Technology", 7, 22.0),
    ("RGTI", "Rigetti Computing", "Technology", 8, 25.0),
    ("AA", "Alcoa", "Materials", 8, 32.0),
    ("BRX", "Brixmor Property Group", "Real Estate", 8, 26.0),
    ("NNN", "NNN REIT", "Real Estate", 8, 42.0),
    ("ADC", "Agree Realty", "Real Estate", 8, 75.0),
    ("FRT", "Federal Realty Investment Trust", "Real Estate", 8, 95.0),
    ("AAL", "American Airlines Group", "Industrials", 8, 12.0),
    ("SAIA", "Saia", "Industrials", 7, 265.0),
    ("KNX", "Knight-Swift Transportation", "Industrials", 7, 42.0),
    ("R", "Ryder System", "Industrials", 7, 165.0),
    ("ALK", "Alaska Air Group", "Industrials", 7, 55.0),
    ("APA", "APA Corp", "Energy", 8, 22.0),
    ("DINO", "HF Sinclair", "Energy", 8, 42.0),
    ("LEU", "Centrus Energy", "Energy", 4, 240.0),
    ("UEC", "Uranium Energy", "Energy", 4, 9.0),
    ("JAZZ", "Jazz Pharmaceuticals", "Health Care", 8, 130.0),
    ("CRL", "Charles River Laboratories", "Health Care", 8, 160.0),
    ("LYFT", "Lyft", "Industrials", 8, 19.0),
    ("SIRI", "Sirius XM Holdings", "Communication Services", 8, 24.0),
    ("MTCH", "Match Group", "Communication Services", 8, 32.0),
    ("WING", "Wingstop", "Consumer Discretionary", 8, 290.0),
    ("LAD", "Lithia Motors", "Consumer Discretionary", 8, 320.0),
    ("BWA", "BorgWarner", "Consumer Discretionary", 8, 38.0),
    ("STAG", "STAG Industrial", "Real Estate", 7, 37.0),
    ("FR", "First Industrial Realty Trust", "Real Estate", 7, 52.0),
    ("ETSY", "Etsy", "Consumer Discretionary", 7, 65.0),
    ("AN", "AutoNation", "Consumer Discretionary", 7, 190.0),
    ("QRVO", "Qorvo", "Technology", 7, 75.0),
    ("AMKR", "Amkor Technology", "Technology", 7, 28.0),
    ("PATH", "UiPath", "Technology", 7, 13.0),
    ("LCID", "Lucid Group", "Consumer Discretionary", 7, 20.0),
    ("MHK", "Mohawk Industries", "Consumer Discretionary", 7, 115.0),
    ("GXO", "GXO Logistics", "Industrials", 6, 50.0),
    ("ACHR", "Archer Aviation", "Industrials", 6, 10.0),
    ("SAIC", "SAIC", "Industrials", 5, 110.0),
    ("CZR", "Caesars Entertainment", "Consumer Discretionary", 6, 28.0),
    ("MAT", "Mattel", "Consumer Discretionary", 6, 19.0),
    ("KMX", "CarMax", "Consumer Discretionary", 6, 42.0),
    ("QS", "QuantumScape", "Consumer Discretionary", 6, 10.0),
    ("VFC", "VF Corp", "Consumer Discretionary", 6, 15.0),
    ("TFX", "Teleflex", "Health Care", 6, 130.0),
    ("S", "SentinelOne", "Technology", 6, 18.0),
    ("MARA", "MARA Holdings", "Technology", 6, 16.0),
    ("SOUN", "SoundHound AI", "Technology", 5, 12.0),
    ("BILL", "BILL Holdings", "Technology", 5, 50.0),
    ("QLYS", "Qualys", "Technology", 5, 135.0),
    ("BOX", "Box Inc", "Technology", 5, 33.0),
    ("WEX", "WEX Inc", "Technology", 5, 130.0),
    ("ENPH", "Enphase Energy", "Technology", 5, 38.0),
    ("RIOT", "Riot Platforms", "Technology", 5, 14.0),
    ("CORZ", "Core Scientific", "Technology", 5, 16.0),
    ("CLF", "Cleveland-Cliffs", "Materials", 5, 10.0),
    ("SEE", "Sealed Air", "Materials", 5, 33.0),
    ("FMC", "FMC Corp", "Materials", 5, 40.0),
    ("CE", "Celanese", "Materials", 6, 55.0),
    ("OSCR", "Oscar Health", "Health Care", 5, 20.0),
    ("SRPT", "Sarepta Therapeutics", "Health Care", 4, 40.0),
    ("STNE", "StoneCo", "Financials", 5, 17.0),
    ("THO", "Thor Industries", "Consumer Discretionary", 5, 95.0),
    ("LEA", "Lear Corp", "Consumer Discretionary", 5, 95.0),
    ("BC", "Brunswick", "Consumer Discretionary", 4, 60.0),
    ("ANF", "Abercrombie & Fitch", "Consumer Discretionary", 4, 85.0),
    ("PVH", "PVH Corp", "Consumer Discretionary", 4, 75.0),
    ("GPS", "Gap Inc", "Consumer Discretionary", 8, 22.0),
    ("EEFT", "Euronet Worldwide", "Technology", 4, 100.0),
    ("TENB", "Tenable Holdings", "Technology", 4, 33.0),
    ("GLOB", "Globant", "Technology", 4, 90.0),
    ("AI", "C3.ai", "Technology", 2, 16.0),
    ("CLSK", "CleanSpark", "Technology", 3, 11.0),
    ("RXRX", "Recursion Pharmaceuticals", "Health Care", 3, 7.0),
    ("CVI", "CVR Energy", "Energy", 3, 28.0),
    ("RUN", "Sunrun", "Technology", 3, 12.0),
    ("PL", "Planet Labs", "Industrials", 3, 9.0),
    ("HOG", "Harley-Davidson", "Consumer Discretionary", 3, 25.0),
    ("CPRI", "Capri Holdings", "Consumer Discretionary", 3, 22.0),
    ("OGN", "Organon", "Health Care", 3, 12.0),
    ("SEDG", "SolarEdge Technologies", "Technology", 2, 30.0),
    ("BBAI", "BigBear.ai", "Technology", 2, 6.0),
    ("RPD", "Rapid7", "Technology", 2, 22.0),
    ("PLUG", "Plug Power", "Industrials", 2, 2.0),
    ("LUNR", "Intuitive Machines", "Industrials", 2, 12.0),
    ("JBLU", "JetBlue Airways", "Industrials", 2, 5.0),
    ("CLOV", "Clover Health", "Health Care", 2, 3.0),
    ("FSLR", "First Solar", "Technology", 22, 200.0),
    ("ZBRA", "Zebra Technologies", "Technology", 15, 290.0),
    ("HPQ", "HP Inc", "Technology", 25, 27.0),
    ("STM", "STMicroelectronics", "Technology", 25, 28.0),
    ("DOCU", "Docusign", "Technology", 16, 80.0),
    ("NICE", "NICE Ltd ADR", "Technology", 10, 155.0),
    ("PCTY", "Paylocity", "Technology", 10, 185.0),
    ("XYZ", "Block Inc", "Financials", 45, 72.0),
    ("PYPL", "PayPal Holdings", "Financials", 70, 70.0),
    ("TTWO", "Take-Two Interactive", "Communication Services", 45, 250.0),
    ("WBD", "Warner Bros. Discovery", "Communication Services", 30, 12.0),
    ("NWSA", "News Corp Class A", "Communication Services", 17, 30.0),
    ("SBAC", "SBA Communications", "Real Estate", 25, 230.0),
    ("KOF", "Coca-Cola FEMSA ADR", "Consumer Staples", 20, 95.0),
    ("BJ", "BJ's Wholesale Club", "Consumer Staples", 14, 105.0),
    ("TSN", "Tyson Foods", "Consumer Staples", 20, 57.0),
    ("DRI", "Darden Restaurants", "Consumer Discretionary", 25, 215.0),
    ("ODFL", "Old Dominion Freight Line", "Industrials", 35, 165.0),
    ("DOV", "Dover", "Industrials", 25, 180.0),
    ("XYL", "Xylem", "Industrials", 30, 125.0),
    ("ALLE", "Allegion", "Industrials", 12, 140.0),
    ("PCAR", "PACCAR", "Industrials", 50, 96.0),
    ("FDX", "FedEx", "Industrials", 55, 230.0),
    ("ED", "Consolidated Edison", "Utilities", 35, 100.0),
    ("WEC", "WEC Energy Group", "Utilities", 35, 108.0),
    ("FE", "FirstEnergy", "Utilities", 25, 42.0),
    ("TLN", "Talen Energy", "Utilities", 15, 330.0),
    ("CARR", "Carrier Global", "Industrials", 55, 65.0),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="data/top500.csv")
    ap.add_argument("--size", type=int, default=500)
    ap.add_argument("--as-of", default=date.today().isoformat())
    args = ap.parse_args()

    seen: dict[str, tuple] = {}
    dupes: list[str] = []
    for row in COMPANIES:
        sym = row[0].upper()
        if sym in seen:
            dupes.append(sym)
            continue
        seen[sym] = row
    if dupes:
        print(f"warning: dropped {len(dupes)} duplicate symbol(s): {', '.join(sorted(set(dupes)))}")

    # Rank 1 = most valuable. Tie-break alphabetically so the ordering is
    # deterministic -- the draft's fairness proof depends on stable ranks.
    ordered = sorted(seen.values(), key=lambda r: (-r[3], r[0]))
    if len(ordered) < args.size:
        print(
            f"warning: only {len(ordered)} companies listed, fewer than the requested "
            f"{args.size}. The draft will use pool_size={len(ordered)}; either add names "
            f"here or lower `draft.pool_size` in config/competition.yaml."
        )
    ordered = ordered[: args.size]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["# as_of", args.as_of, "metric", "market_cap",
                    "source", "scripts/build_top500.py"])
        w.writerow(["rank", "symbol", "name", "sector", "market_cap_usd", "share_price"])
        for i, (sym, name, sector, cap_b, px) in enumerate(ordered, start=1):
            w.writerow([i, sym, name, sector, f"{cap_b * 1e9:.0f}", f"{px:.2f}"])

    sectors: dict[str, int] = {}
    for _, _, sector, _, _ in ordered:
        sectors[sector] = sectors.get(sector, 0) + 1
    print(f"wrote {len(ordered)} rows -> {out}")
    print("sector mix:")
    for s, n in sorted(sectors.items(), key=lambda kv: -kv[1]):
        print(f"  {n:4d}  {s}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
